import type { Metadata } from "next";
import { Cormorant, Mulish } from "next/font/google";
import "./globals.css";

const cormorant = Cormorant({
  weight: ['600'],
  subsets: ['latin'],
  variable: '--font-heading',
})

const mulish = Mulish({
  weight: ['300'],
  subsets: ['latin'],
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cormorant.variable} ${mulish.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
